### ISSUE TITLE
KLS :RFQ Process... Create & Invite...no email body it have one 1 line of text

### ISSUE THREAD

**Issue by nakarat-p** [hieplq/motive#16]
Customer request body of email too.
So can we have Email Template like Process ..Create Email Result?

**Comment by hieplq** [comment]
need to apply new 2pack on plugin

https://github.com/hieplq/idempiere/commit/9d73d7ff2c5823f2e2f8aaf65c4a8dbddbc843d7

https://github.com/motiveth/th.motive.kls.rfq/commit/1704ab7304e87c36641ffe485863570595e7bc6b
